##=============================================================================
##
##  The contents of this file are covered by the Viskores license. See
##  LICENSE.txt for details.
##
##  By contributing to this file, all contributors agree to the Developer
##  Certificate of Origin Version 1.1 (DCO 1.1) as stated in DCO.txt.
##
##=============================================================================

NAME
  viskores_python_bindings
GROUPS
  PythonBindings
PRIVATE_DEPENDS
  viskores_cont
NO_TESTING
