name: CI
on:
  push:
    branches:
      - main
      - release*
  pull_request:
    branches:
      - main
      - release*

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    defaults:
      run:
        shell: pwsh
    env:
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_BUILD_TYPE: Release
      VISKORES_SETTINGS: serial
      VCVARSALL: C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat
      VCVARSPLATFORM: x64
      VCVARSVERSION: 14.29
    steps:
      - uses: actions/checkout@v4
      - name: Set general vars
        run: |
          "CI_COMMIT_SHA=$env:GITHUB_SHA" >> $env:GITHUB_ENV
          "CI_PROJECT_DIR=$env:GITHUB_WORKSPACE" >> $env:GITHUB_ENV
          "$pwd.Path\.gitlab" >> $env:GITHUB_PATH

      - name: Configure
        run: |
          cmake --version
          cmake -V -P .gitlab/ci/config/ninja.cmake
          Invoke-Expression -Command .gitlab/ci/config/vcvarsall.ps1
          Get-ChildItem env:
          cmake -V -P .github/github_ci_setup.cmake
          ctest -VV -S .gitlab/ci/ctest_configure.cmake

      - name: Build
        run: ctest -VV -S .gitlab/ci/ctest_build.cmake

      - name: Test
        run: ctest -VV -S .gitlab/ci/ctest_test.cmake
