##============================================================================
##  The contents of this file are covered by the Viskores license. See
##  LICENSE.txt for details.
##
##  By contributing to this file, all contributors agree to the Developer
##  Certificate of Origin Version 1.1 (DCO 1.1) as stated in DCO.txt.
##============================================================================

name: external
on:
  push:
  pull_request_target:

permissions:
  contents: read

jobs:
  generate_statuses:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Kitware/cdash-status@697751fc655b300a9e16e285f2e2ee981f59e45a # release
        with:
          project: Viskores
